### ISSUE TITLE
Tested with Laravel 5.5

### ISSUE THREAD

**Issue by eilifjohansen** [kneipp/socialite-wrapper#1]
I just tested socialite-wrapper with Laravel 5.5 and it works great!
You might want to add "Laravel 5.5" to the README file.

Keep up the good work! 👍

**Comment by kneipp** [comment]
Ok @eilifjohansen! 
To be honest with you I've missed your message notification as you can see =)
I'll updated this package to Laravel 5.7 soon.
Thank you, for feedback!
